<a href="https://colab.research.google.com/github/harshaelon/AI_Agents/blob/main/Multiclass_classification_using_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

%matplotlib inline

In [ ]:
from sklearn.datasets import make_classification

# using the above library fucntion we can define how many output classes we need
# and it will create the dataset in such a way that it's already standardized
# means we dont need to do any standardization here.

In [ ]:
X,y = make_classification(n_samples=1000 , n_features=10 , n_informative = 3 , n_classes = 3 , random_state = 1)

In [ ]:
y

array([2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 0, 1, 2, 1, 2, 1, 1, 2, 0,
       1, 2, 0, 1, 1, 1, 0, 2, 1, 2, 0, 0, 1, 2, 1, 1, 2, 0, 1, 1, 2, 1,
       2, 0, 1, 2, 1, 1, 2, 1, 2, 0, 2, 2, 1, 0, 2, 2, 0, 2, 2, 1, 0, 1,
       2, 1, 1, 0, 0, 0, 2, 1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 0, 1, 1, 0, 1,
       1, 1, 2, 2, 2, 1, 1, 2, 0, 2, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1,
       0, 1, 0, 2, 2, 0, 0, 0, 2, 1, 2, 2, 2, 0, 0, 0, 0, 1, 0, 1, 1, 2,
       1, 0, 2, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 2, 2, 2,
       1, 0, 2, 2, 1, 0, 0, 0, 1, 1, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 1, 0,
       1, 2, 2, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 1, 1, 2, 1,
       1, 1, 2, 2, 2, 2, 1, 1, 2, 0, 2, 2, 1, 2, 0, 1, 2, 2, 2, 2, 1, 0,
       1, 1, 2, 0, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1,
       0, 0, 1, 2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 2, 2,
       2, 1, 0, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 0, 2, 1, 1, 0, 2, 1,
       1, 1, 2, 0, 1, 0, 2, 1, 0, 2, 2, 2, 2, 0, 1,

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train , X_test , y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logistic = LogisticRegression(multi_class = 'ovr')

In [ ]:
logistic.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [ ]:
y_pred = logistic.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [ ]:
score = accuracy_score(y_test,y_pred)

print(score)

confusion = confusion_matrix(y_test,y_pred)

print(confusion)


classi = classification_report(y_test,y_pred)

print(classi)


0.7333333333333333
[[80  7 25]
 [20 70  7]
 [ 4 17 70]]
              precision    recall  f1-score   support

           0       0.77      0.71      0.74       112
           1       0.74      0.72      0.73        97
           2       0.69      0.77      0.73        91

    accuracy                           0.73       300
   macro avg       0.73      0.74      0.73       300
weighted avg       0.74      0.73      0.73       300



# Hyperparameter Tuning

In [ ]:
model = LogisticRegression(multi_class='ovr')

# working with parameters
penalty = ['l1','l2','elasticnet']


c_value =  [100,10,1.0,0.1,0.01]

solver = ['newton-cg','lbfgs','liblinear','sag','saga']

max_iter = [100,150,200,250]


In [ ]:
dict(penalty = penalty , C = c_value , solver=solver)

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}

In [ ]:
params = dict(penalty = penalty , C = c_value , solver=solver)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold()
grid = GridSearchCV(estimator = model , param_grid = params, scoring = 'accuracy', cv =cv , n_jobs=-1)

In [ ]:
grid.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1169, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(multi_class='ovr'), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [ ]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [ ]:
grid.best_score_

0.7057142857142857

In [ ]:
y_pred = grid.predict(X_test)

In [ ]:
score = accuracy_score(y_test,y_pred)

print(score)

confusion = confusion_matrix(y_test,y_pred)

print(confusion)


classi = classification_report(y_test,y_pred)

print(classi)


0.7233333333333334
[[80  5 27]
 [23 67  7]
 [ 5 16 70]]
              precision    recall  f1-score   support

           0       0.74      0.71      0.73       112
           1       0.76      0.69      0.72        97
           2       0.67      0.77      0.72        91

    accuracy                           0.72       300
   macro avg       0.73      0.72      0.72       300
weighted avg       0.73      0.72      0.72       300

